Allow raster bands in Collection's item assets
stac-extensions/raster pull request #16
Opened 2021-06-01 19:56 UTC by kylebarron

This PR modifies the JSON Schema to allow raster band information in a Collection's `item_assets` key. This is identical to what the EO extension does: https://github.com/stac-extensions/eo/blob/89da8dc305f43cf34980b3d52f3bfbbc4d8c88d4/json-schema/schema.json#L85-L96

2021-06-02 07:51 UTC, emmanuelmathot requested changes
LGTM. Do you have an example to put in the repo?

2021-06-02 16:30 UTC, kylebarron commented
I don't have an example off hand. I could take one of the existing planet or sentinel item examples and convert it to a collection, moving `assets` to `item_assets`.

2021-06-30 09:47 UTC, m-mohr approved these changes
Looks good to me.

I don't think we necessarily need an example, most other extensions also don't have one at hand. It's the normal behavior in STAC anyway and there's nothing specific in raster.

2021-06-30 14:27 UTC, emmanuelmathot approved these changes

2021-06-30 14:27 UTC, merged